[package]
edition = "2021"
name = "custom-types"
version = "0.1.0"

[dependencies]
# Clorinde
clorinde = { path = "custom_types_codegen", package = "custom_types_codegen" }
# Async
tokio = { version = "1.28.1", features = ["macros", "rt-multi-thread"] }
futures = "0.3.28"
