[package]
name = "auto-build"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#cornucopia = { path = "cornucopia" }

# Async
tokio = { version = "1.24.2", features = ["full"] }
futures = "0.3.25"

# Postgres interaction
tokio-postgres = "0.7.7"
## Connection pooling
deadpool-postgres = "0.10.4"

codegen = { path = "auto_build_codegen", package = "auto_build_codegen" }
